version: '2'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    web:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./scripts:/scripts
            - ./logs/symfony:/var/www/symfony/app/logs
            - .sonar_cache:/root/.sonar/cache
    nginx:
        build: nginx
        volumes_from:
            - web
        volumes:
            - ./logs/nginx/:/var/log/nginx
    selenium:
        image: elgalu/selenium
        environment:
          - SELENIUM_HUB_PORT=4444
          - VNC_FROM_PORT
          - VNC_TO_PORT
          - SCREEN_WIDTH=1300
          - SCREEN_HEIGHT=999
          - GRID=false
          - CHROME=true
          - FIREFOX=false
          - RC_CHROME=false
          - RC_FIREFOX=false    